version: "3.9"

services:
  api:
    image: thecodingmachine/php:8.2-v4-apache
    environment:
      - APACHE_DOCUMENT_ROOT=public/
    volumes:
      - "./:/var/www/html/"
    ports:
      - 8000:80

  db:
    restart: always
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7.0
    volumes:
      - redis-data:/var/lib/redis:rw

volumes:
  db-data: {}
  redis-data: {}
